default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  host: db
  username: teste
  password: teste

development:
  <<: *default
  database: teste

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: teste
  password: teste
