default: &default
  adapter: sqlserver
  username: raphael
  password: raphael23
  host: wisehands.ddns.net
  port: 4433
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>
  timeout: 500000

development:
  <<: *default
  database: dbCandidatesLinkedin

test:
  <<: *default
  database: <%= ENV['SQLSERVER_DATABASE_NAME'] || 'database_name' %>_test

production:
  <<: *default
  database: <%= ENV['SQLSERVER_DATABASE_NAME'] || 'database_name' %>_production
